export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const REQUEST_VIDEOS_PENDING = 'REQUEST_VIDEOS_PENDING'
export const REQUEST_VIDEOS_SUCCESS = 'REQUEST_VIDEOS_SUCCESS'
export const REQUEST_VIDEOS_FAILED = 'REQUEST_VIDEOS_FAILED'